# The ID of the dataset you created above.
dataset: doom-mistral

conversation: {}

# The Hugging Face model name of the base model.
base_model: mistralai/Mistral-7B-v0.1

learning_rate: 1.0e-4
epochs: 2.0

wandb_entity: your_username
wandb_api_key: your_api_key
wandb_project: doom-mistral

model_id: doom-mistral
